export const CREATE_REGISTER_START = 'CREATE_REGISTER_START'
export const CREATE_REGISTER_SUCCESS = 'CREATE_REGISTER_SUCCESS'
export const CREATE_REGISTER_FAILURE = 'CREATE_REGISTER_FAILURE'

export const CREATE_LOGIN_START = 'CREATE_LOGIN_START'
export const CREATE_LOGIN_SUCCESS = 'CREATE_LOGIN_SUCCESS'
export const CREATE_LOGIN_FAILURE = 'CREATE_LOGIN_FAILURE'