export const CREATE_SUBSCRIBE_START = 'CREATE_SUBSCRIBE_START';
export const CREATE_SUBSCRIBE_SUCCESS = 'CREATE_SUBSCRIBE_SUCCESS';
export const CREATE_SUBSCRIBE_FAILURE = 'CREATE_SUBSCRIBE_FAILURE';
