version: '3'

services:
  front:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: triplytrip
    volumes:
      - .:/var/www/triplytrip
    ports:
      - "4000:4000"
    command: npm run dev

