version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: triplytrip
    volumes:
      - .:/var/www/triplytrip
    ports:
      - "4000:4000"
    command: npm start
  db:
    build:
      context: .
      dockerfile: ../triplytrip-backend/Dockerfile
    volumes: 
    - .:/var/www/triplytrip-backend
    ports: 
    - "8000:8000"
    command: npm run dev

