export const GET_TOP_DESTINATIONS_START = 'GET_TOP_DESTINATIONS_START';
export const GET_TOP_DESTINATIONS_SUCCESS = 'GET_TOP_DESTINATIONS_SUCCES';
export const GET_TOP_DESTINATIONS_FAILURE = 'GET_TOP_DESTINATIONS_FAILURE';


export const GET_EVENTS_SRART = 'GET_EVENTS_SRART';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_SUCCESS';

export const GET_CATEGORIES_START = 'GET_CATEGORIES_START'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE'

export const GET_CITIES_START = 'GET_CITIES_START'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE'

export const SET_DEFAULT_STATUSES = 'SET_DEFAULT_STATUSES'
export const SET_RESPONSE_SUCCESS_STATUSES = 'SET_RESPONSE_SUCCESS_STATUSES'
export const SET_RESPONSE_FAILURE_STATUSES = 'SET_RESPONSE_FAILURE_STATUSES'