export const GET_TOP_DESTINATIONS_START = 'GET_TOP_DESTINATIONS_START';
export const GET_TOP_DESTINATIONS_SUCCESS = 'GET_TOP_DESTINATIONS_SUCCES';
export const GET_TOP_DESTINATIONS_FAILURE = 'GET_TOP_DESTINATIONS_FAILURE';

