export const CREATE_LISTING_START = 'CREATE_LISTING_START';
export const CREATE_LISTING_SUCCESS = 'CREATE_LISTING_SUCCESS';
export const CREATE_LISTING_FAILURE = 'CREATE_LISTING_FAILURE';

export const GET_USER_LISTING_START = 'GET_USER_LISTING_START';
export const GET_USER_LISTING_SUCCESS = 'GET_USER_LISTING_SUCCESS';
export const GET_USER_LISTING_FAILURE = 'GET_USER_LISTING_FAILURE';

export const DELETE_USER_LISTING_START = 'DELETE_USER_LISTING_START';
export const DELETE_USER_LISTING_SUCCESS = 'DELETE_USER_LISTING_SUCCESS';
export const DELETE_USER_LISTING_FAILURE = 'DELETE_USER_LISTING_FAILURE';
