export const GET_PLACES_START = 'GET_PLACES_START';
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS';
export const GET_PLACES_FAILURE = 'GET_PLACES_FAILURE';

export const GET_PLACE_DETAIL_BY_ID_START = 'GET_PLACE_DETAIL_BY_ID_START';
export const GET_PLACE_DETAIL_BY_ID_SUCCESS = 'GET_PLACE_DETAIL_BY_ID_SUCCESS';
export const GET_PLACE_DETAIL_BY_ID_FAILURE = 'GET_PLACE_DETAIL_BY_ID_FAILURE';
