export const GET_ARTICLE_DETAIL_START = 'GET_ARTICLE_DETAIL_START';
export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS';
export const GET_ARTICLE_DETAIL_FAILURE = 'GET_ARTICLE_DETAIL_FAILURE';


export const GET_ARTICLE_DETAIL_BY_ID_START = 'GET_ARTICLE_DETAIL_BY_ID_START';
export const GET_ARTICLE_DETAIL_BY_ID_SUCCESS = 'GET_ARTICLE_DETAIL_BY_ID_SUCCESS';
export const GET_ARTICLE_DETAIL_BY_ID_FAILURE = 'GET_ARTICLE_DETAIL_BY_ID_FAILURE';


export const GET_ARTICLES_BY_PAGE_START = 'GET_ARTICLES_BY_PAGE_START';
export const GET_ARTICLES_BY_PAGE_SUCCESS = 'GET_ARTICLES_BY_PAGE_SUCCESS';
export const GET_ARTICLES_BY_PAGE_FAILURE = 'GET_ARTICLES_BY_PAGE_FAILURE';



export const GET_ARTICLES_BY_ID_START = 'GET_ARTICLES_BY_ID_START';
export const GET_ARTICLES_BY_ID_SUCCESS = 'GET_ARTICLES_BY_ID_SUCCESS';
export const GET_ARTICLES_BY_ID_FAILURE = 'GET_ARTICLES_BY_ID_FAILURE';


