export const GET_ARTICLE_DETAIL_START = 'GET_ARTICLE_DETAIL_START';
export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS';
export const GET_ARTICLE_DETAIL_FAILURE = 'GET_ARTICLE_DETAIL_FAILURE';


export const GET_ARTICLE_DETAIL_BY_ID_START = 'GET_ARTICLE_DETAIL_BY_ID_START';
export const GET_ARTICLE_DETAIL_BY_ID_SUCCESS = 'GET_ARTICLE_DETAIL_BY_ID_SUCCESS';
export const GET_ARTICLE_DETAIL_BY_ID_FAILURE = 'GET_ARTICLE_DETAIL_BY_ID_FAILURE';

